### ISSUE TITLE
Regular expression vulnerability

### ISSUE THREAD

**Issue by ehmicky** [dperini/nwmatcher#112]
Is there a fix for the RegExp vulnerability reported by https://snyk.io/vuln/npm:nwmatcher:20180305?

**Comment by dperini** [comment]
@ehmicky yes, a fix replacing multiple repeated instances of the "\s*" pattern was released same day of disclosure and publishing (5 March 2018) by this commit https://github.com/dperini/nwmatcher/commit/9dcc2b039beeabd18327a5ebaa537625872e16f0.

 Anyway `nwmatcher` have always performed a cleanup and normalization step of the input string before passing it to the validation step where the input is scanned and parsed by those Regular Expressions.

Actually no proof of vulnerability has been shown against `nwmatcher`, it was just an automated scanning for repeated "\s*" instances in the Regular Expressions found in the source code, which just indicates a potential presence of that pattern and the possible issue.

Why are you asking ? Did you find problems with that or can you show evidence of the issue ?

**Comment by ehmicky** [comment]
Great this is fixed!

However I'm asking because Snyk is still reporting `There is no fixed version for nmwatcher.` and `Affecting nwmatcher package, ALL versions`. Which means all projects that depend on `nwmatcher` get flagged as vulnerable.

I'm not 100% familiar with Snyk, maybe there's a way to report the issue has been fixed?

**Comment by dperini** [comment]
I contacted them asking to remove the warning against `nwmatcher` or at  least indicate the problem has been fixed since March 5th.

Thank you.

**Comment by ehmicky** [comment]
Could you please leave the issue open until they fix it and reply once they do? This would allow us to now when we can upgrade our dependencies. Thanks!

**Comment by dperini** [comment]
@ehmicky hey you should write to the culprit of the state of things, I told you "nwmatcher" was never affected, I showed you that I did my best to follow their suggestion anyway and linked you to the commit where I fixed the "potential" issue and in their page they self state "LOW SEVERITY".

Hope you understand the difference between Open Source (my free work) and the pricing of a service subscription, their attempt to make money is a bit of an harassment to me and you too.

That said, here is what you asked ... Reopened the issue and lying to my users.
Is this what you wanted ?

**Comment by ehmicky** [comment]
Nessun problema, tutto bene.

I understand your frustration as the original vulnerability is actually not one, you fixed it right away and this is an external company.

The reason I was asking to keep it open was to give you the opportunity to notify users once you get an answer from Snyk. I understand though if you think users should instead directly setup notifications with Snyk.

Thanks again for the time you spent on this project.

**Comment by dperini** [comment]
I am upset since I already got an answer from them the same day that I released the fix the 5th of March, saying that they scanned my repository again and that the fix was good enough since the new scan was negative.

The problem is that after 45 days things have not changed, "nwmatcher" is still marked as vulnerable (`ALL Versions`) in their pages even if it has never been proven the issue exist and you are the third person I have had to give an explanation about these false information.

That is no good for NPM nor for users.

**Comment by dperini** [comment]
@ehmicky Up to now I wrote 4 e-mails to the contacts I have for Snyk.io without success.
They are not responsive, they want to keep these false and misleading info on their pages.
However, despite what they may say there is no known vulnerable version of "nnwmatcher".

This says a lot about the correctness of their supposed vulnerabilities reviews for packages published on NPM. It could have been a nice service to the community but managed in this way turned it in just another Internet SCAM.

I prefer to close this issue since we are just terrifying our users without any real reason or evidence.
