### ISSUE TITLE
Selectors on unattached trees

### ISSUE THREAD

**Issue by muodov** [dperini/nwmatcher#113]
I get a different result when using nwmatcher and native `querySelectorAll()`. See this fiddle: https://jsfiddle.net/n2jhy7ga/5/

Is this an expected behaviour? It seems to reproduce only in headless version.

Copying the code below just in case:

```javascript
var cont = document.createElement('div');
cont.id = 'contid';

var el = document.createElement('div');
el.id = 'myid';

var inp = document.createElement('input');
inp.type = 'radio';

el.appendChild(inp);
cont.appendChild(el);

var selector = '#contid input[type=radio]';

var res = NW.Dom.select(selector, cont);
var exp = cont.querySelectorAll(selector);

console.log(res === exp);
console.log('result', res); // empty list
console.log('expected', exp); // non-empty list

```

**Comment by dperini** [comment]
@mudov,
if it is not a problem for your requirements, you should switch into using "nwsapi,js" which is the new selector engine supporting almost every single feature of the new Selectors Level 4 API.
It is available both in my repository and on NPM, the "nwsapi.js" package is the one currently used in nodejs/jsdom if it happens you are working in those headless environment.

The problem is bound to scoping mechanism that changed.
Let me know if changing to "nwsapi.js" works as expected.
Maybe I will port these changes in "nwmatcher" 1.4.5 too.

**Comment by muodov** [comment]
Thanks for the tip! We're using a slightly patched version of the library, but nwsapi seems to have solved the issue for us.
Please feel free to close this ticket if you like.
